Repository Project-Qriz/iOS, pull requests merged in 2025-03, with the labels that each got.

#33 FEAT: 코디네이터 연결 + 탭바 구현
  QRIZ.xcodeproj/project.pbxproj
  QRIZ/App/SceneDelegate.swift
  QRIZ/Coordinator/AppCoordinator.swift
  QRIZ/Feature/Home/HomeCoordinator.swift
  QRIZ/Feature/Home/HomeViewController.swift
  QRIZ/Feature/Home/HomeViewModel.swift
  QRIZ/Feature/Home/ViewController.swift
  QRIZ/Feature/Login/LoginCoordinator.swift
  QRIZ/Feature/MistakeNote/MistakeNoteCoordinator.swift
  QRIZ/Feature/MistakeNote/MistakeNoteViewController.swift
  QRIZ/Feature/MyPage/MyPageCoordinator.swift
  QRIZ/Feature/MyPage/MyPageViewController.swift
  QRIZ/Feature/TabBar/TabBarCoordinator.swift
  QRIZ/Feature/Textbook/TextbookCoordinator.swift
  QRIZ/Feature/Textbook/TextbookViewController.swift
  QRIZ/Resources/Assets.xcassets/TabBar/Contents.json
  QRIZ/Resources/Assets.xcassets/TabBar/home.imageset/Contents.json
  QRIZ/Resources/Assets.xcassets/TabBar/home.imageset/Home.png
  QRIZ/Resources/Assets.xcassets/TabBar/home.imageset/Home@2x.png
  QRIZ/Resources/Assets.xcassets/TabBar/home.imageset/Home@3x.png
  QRIZ/Resources/Assets.xcassets/TabBar/mistakeNote.imageset/Contents.json
  QRIZ/Resources/Assets.xcassets/TabBar/mistakeNote.imageset/MistakeNote.png
  QRIZ/Resources/Assets.xcassets/TabBar/mistakeNote.imageset/MistakeNote@2x.png
  QRIZ/Resources/Assets.xcassets/TabBar/mistakeNote.imageset/MistakeNote@3x.png
  QRIZ/Resources/Assets.xcassets/TabBar/myPage.imageset/Contents.json
  QRIZ/Resources/Assets.xcassets/TabBar/myPage.imageset/MyPage.png
  QRIZ/Resources/Assets.xcassets/TabBar/myPage.imageset/MyPage@2x.png
  QRIZ/Resources/Assets.xcassets/TabBar/myPage.imageset/MyPage@3x.png
  QRIZ/Resources/Assets.xcassets/TabBar/selectedMistakeNote.imageset/Contents.json
  QRIZ/Resources/Assets.xcassets/TabBar/selectedMistakeNote.imageset/selectedMistakeNote.png
  QRIZ/Resources/Assets.xcassets/TabBar/selectedMistakeNote.imageset/selectedMistakeNote@2x.png
  QRIZ/Resources/Assets.xcassets/TabBar/selectedMistakeNote.imageset/selectedMistakeNote@3x.png
  QRIZ/Resources/Assets.xcassets/TabBar/selectedTextbook.imageset/Contents.json
  QRIZ/Resources/Assets.xcassets/TabBar/selectedTextbook.imageset/selectedTextbook.png
  QRIZ/Resources/Assets.xcassets/TabBar/selectedTextbook.imageset/selectedTextbook@2x.png
  QRIZ/Resources/Assets.xcassets/TabBar/selectedTextbook.imageset/selectedTextbook@3x.png
  QRIZ/Resources/Assets.xcassets/TabBar/textBook.imageset/Contents.json
  QRIZ/Resources/Assets.xcassets/TabBar/textBook.imageset/TextBook.png
  QRIZ/Resources/Assets.xcassets/TabBar/textBook.imageset/TextBook@2x.png
  QRIZ/Resources/Assets.xcassets/TabBar/textBook.imageset/TextBook@3x.png
Labels: ✨Feat

#35 FEAT: 프리뷰 테스트 및 로직 수정
  QRIZ/Feature/Onboarding/OnboardingComponents/OnboardingButton.swift
  QRIZ/Feature/Onboarding/PreviewTest/ViewController/PreviewTestViewController.swift
  QRIZ/Feature/Onboarding/PreviewTest/ViewModel/PreviewTestViewModel.swift
  QRIZ/Feature/TempViewController.swift
  QRIZ/Feature/TestComponents/QuestionOptionLabel.swift
  QRIZ/Utils/Model/TestModel/QuestionData.swift
Labels: 🛠️Fix

#37 FIX: 프리뷰 테스트 결과 UI 수정
  QRIZ.xcodeproj/project.pbxproj
  QRIZ/Feature/Onboarding/BeginPreviewTest/ViewController/BeginPreviewTestViewController.swift
  QRIZ/Feature/Onboarding/BeginPreviewTest/ViewModel/BeginPreviewTestViewModel.swift
  QRIZ/Feature/Onboarding/CheckConcept/ViewController/CheckConceptViewController.swift
  QRIZ/Feature/Onboarding/PreviewResult/HostingController/ConceptBarGraphHostingController.swift
  QRIZ/Feature/Onboarding/PreviewResult/HostingController/PreviewResultViewHostingController.swift
  QRIZ/Feature/Onboarding/PreviewResult/HostingController/ScoreCircularChartHostingController.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/BarGraphsView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/ConceptBarGraphView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/IncorrectConceptsRankView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/IncorrectRankView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultBarGraphsView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultConceptView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultIncorrectConceptsRankView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultIncorrectRankView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultInfoView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultScoreCircularChartView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultScoreView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultTitleLabel.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/PreviewResultView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/ScoreCircularChartView.swift
  QRIZ/Feature/Onboarding/PreviewResult/View/SingleSupplementConceptView.swift
  QRIZ/Feature/Onboarding/PreviewResult/ViewController/PreviewResultViewController.swift
  QRIZ/Feature/Onboarding/PreviewResult/ViewModel/PreviewResultViewModel.swift
  QRIZ/Feature/Onboarding/PreviewTest/ViewModel/PreviewTestViewModel.swift
  QRIZ/Feature/TempViewController.swift
  QRIZ/Utils/Model/OnboardingModel/IncorrectCountData.swift
  QRIZ/Utils/Model/OnboardingModel/PreviewConceptsData.swift
  QRIZ/Utils/Model/OnboardingModel/PreviewScoresData.swift
Labels: 🛠️Fix

#40 CONFIG: XCConfig 파일 관련 설정
  .gitignore
  Network/Base/NetworkRequest.swift
  QRIZ.xcodeproj/project.pbxproj
  QRIZ.xcodeproj/xcshareddata/xcschemes/QRIZ-Debug.xcscheme
  QRIZ.xcodeproj/xcshareddata/xcschemes/QRIZ-Release.xcscheme
  QRIZ.xcodeproj/xcshareddata/xcschemes/QRIZ.xcscheme
  QRIZ/SupportingFiles/Info.plist
Labels: ⚙️Config

#41 FIX: 오늘의 공부 디자인 수정
  QRIZ.xcodeproj/project.pbxproj
  QRIZ/Feature/CommonViews/TestNavigatorButton.swift
  QRIZ/Feature/DailyLearn/View/StudyContentCell.swift
  QRIZ/Feature/DailyLearn/ViewController/DailyLearnViewController.swift
  QRIZ/Feature/DailyLearn/ViewModel/DailyLearnViewModel.swift
Labels: 🛠️Fix
